services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    network_mode: bridge
    ports:
      - 8096:8096  # HTTP port
    volumes:
      - ./path/to/jellyfin/config:/config
      - /path/to/media:/media
    restart: unless-stopped
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - WEBUI_PORT=8181
    volumes:
      - ./path/to/qbittorrent/config:/config
      - /path/to/downloads:/downloads
    ports:
      - 8181:8181
      - 6881:6881/udp
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - ./path/to/sonarr/config:/config
      - /path/to/downloads:/downloads
      - /path/to/media/tv:/tv
    ports:
      - 8989:8989
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./radarr/config:/config
      - /path/to/downloads:/downloads
      - /path/to/media/Movies:/movies
    ports:
      - 7878:7878
    restart: unless-stopped
  homarr:
    image: ghcr.io/ajnart/homarr:latest
    container_name: homarr
    volumes:
      - ./path/to/homarr/config:/app/data/config
    ports:
      - 7575:7575
    restart: unless-stopped
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Amsterdam
    volumes:
      - ./path/to/prowlarr/configs/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
